### ISSUE TITLE
Windows serializer issue

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#247]
### Symptoms
on Windows binaries after adding classroom file in 'golem.log`
appears error 

```
2018-03-09 12:57:51 ERROR    golem.client                        b"Task '0084d14d-b8ff-4d9e-86a3-f1beba9136a4' creation failed: KeyError('0084d14d-b8ff-4d9e-86a3-f1beba9136a4',) "
2018-03-09 12:57:51 ERROR    golem.client                        b"Cannot create task {'type': 'Blender', 'name': 'Golem Taskclass', 'timeout': '1:30:00', 'subtask_timeout': '0:30:00', 'subtasks': 5, 'bid': 5.0, 'resources': ['\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_01.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_04.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\._.DS_Store', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\cork.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\officeSupplies.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\pencil_color.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wallClock\\\\textures\\\\wallClock.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\eraser.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\ceilingAirVent_AO.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\books\\\\textures\\\\zapBook.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wastes\\\\textures\\\\crinkledPaper_03.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_bareMetal.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\dustBin\\\\dustBin.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_07.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_brownWood.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\europeMap.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\desks\\\\desks.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wastes\\\\textures\\\\crinkledPaper.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\woodPlanks.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\pencil_brandMask.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\classroom.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\dustBin\\\\textures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\suitcase\\\\suitcase.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_03.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\chairs\\\\chairs.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\radiator\\\\textures\\\\radiator_AO.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\coatStand\\\\coatStand.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\lamps\\\\lamps.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_bluredMetal.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\pencil_colorMask.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_paintedPlasterWall.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_frostedGlass.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_leather.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\blackBoard.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\ReadMe.txt', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_02.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_scratch.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_darkWood.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\__ENV\\\\Garage\\\\Garage.hdr', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\dustBin\\\\textures\\\\dustbin_wireframe.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_wallPaint.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_woodFloor.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wallClock\\\\textures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\books\\\\books.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wastes\\\\wastes.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\ceiling_AO.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\radiator\\\\textures\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_brightWood.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\radiator\\\\radiator.blend', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_05.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\officeSupplies\\\\textures\\\\pencil_glossyMask.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_06.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wastes\\\\textures\\\\crinkledPaper_02.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\_baseTextures\\\\base_paper_01.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\childDrawing_08.png', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\glass.jpg', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\textures\\\\childDrawing\\\\Thumbs.db', '\\\\\\\\vmware-host\\\\Shared Folders\\\\pliki testowe\\\\test files\\\\external assets and textures\\\\classroom\\\\assets\\\\wallClock\\\\wallClock.blend'], 'options': {'output_path': 'C:\\\\Users\\\\ederenn\\\\Documents', 'format': 'PNG', 'resolution': [400, 400], 'frames': '1', 'compositing': False}, 'legacy': False} "
Traceback (most recent call last):
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 605, in create_task
  File "C:\BuildbotWorker\buildpackage_windows\build\golem\client.py", line 511, in task_created
KeyError: '0084d14d-b8ff-4d9e-86a3-f1beba9136a4'
```

In interface it shown warning but Golem continues computations (in logs it seems to be ok)
If not restarted immediately, computations are finished (despite the warning).
Results are shown after restart of an application, task status is finished.

![unnamed](https://user-images.githubusercontent.com/32061891/37210463-0ff83e94-23a9-11e8-8fb2-81d548ca8889.png)

#### Steps to reproduce:
- add a task - classroom file with small resolution 400x400
- wait for warning in interface and leave Golem running
- wait appropriate amount of time for task to be finished 
- restart Golem
-check if task is finished

#### Appeared on:

'GOLEM Version: 0.13.0+dev4.gaa9f2d163 '
'Protocol Version: 24 '
golem_messages Version: 1.16.0 '

**Comment by mfranciszkiewicz** [comment]
`\\vmware-host` is a network path and I don't think we're going to support that in the near future. We should filter out unsupported paths.
